# Generated by Django 5.1.2 on 2024-10-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_accesstoken_user_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessTokenCreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accessTokenExpires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
